# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneStopClick' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OneStopClick
  pod 'Google/SignIn'

  target 'OneStopClick-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneStopClickTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'OneStopClick-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OneStopClick-tvOS


end
